# Open the config by double-clicking the "Install" button for any Humble game.
# Changes are loaded when the file is saved.

# `[library]-sources` is a comma-separated list of game types shown in your GOG Galaxy library. Duplicates are resolved according to the specified order.
# Available options:
    # drm-free: games with direct downloads for Windows, macOS, or Linux visible at https://www.humblebundle.com/home/library
    # keys: games defined as keys to be redeemed in third-party services (Steam/Origin/Uplay/Epic/Battle.net).
# Modify the list to manage your Humble Bundle collection in GOG Galaxy library or change the priority order; games from higher-priority types are preferred.

# `[library]-show_revealed_keys` controls whether already revealed key-based games are shown. Ignored when `keys` is not in the `sources` list.
# Set to true to show all keys.
# Default is false, because if a game key is redeemed on your Steam/Origin/Uplay/Battle.net account, it should also be visible in the relevant Galaxy integration.
# Note: a revealed key does not mean it is activated (redeemed) in the appropriate Steam/Origin account.

# `[installed]-search_dirs`: list of directory paths used for installed-game lookup. Environment variables are supported.
# On Windows, both forward slashes and double backslashes are supported.
# For example:
# search_dirs = [
    # 'D:\\Games\\HumbleBundle',
    # '%programW6432%/Games',  # Program Files/Games
    # '%programfiles(x86)%', # Program Files(x86)
# ]
# ===

# This config file is deprecated; use the GUI by double-clicking the "Install" button for any Humble game.
# If you still want to edit the raw config, it is located at:
#     Windows: %LocalAppData%\galaxy-hb\galaxy-humble-config.ini
#     Mac: ~/.config.galaxy-humble.cfg